[package]
name = "sqilo-derive"
version = "0.1.0"
edition = "2024"
description = "(WIP) A derive macro over rusqlite which allows you to get started with a database fastly. You probably are looking for sqilo though."
license = "MIT OR Apache-2.0"


[lib]
proc-macro = true

[dependencies]
convert_case = "0.11.0"
heck = "0.5.0"
ident_case_conversions = "1.0.0"
itertools = "0.14.0"
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = { version = "2.0.101", features = ["full"] }
